import mongoose from "mongoose";

const userRoadmapSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      unique: true, // one roadmap per user
    },

    // Career path e.g. "fsd", "ds", "cybersecurity"
    careerPath: {
      type: String,
      required: true,
    },

    // Total days in this roadmap
    totalDays: {
      type: Number,
      required: true,
    },

    // Full roadmap structure generated by roadmapEngine
    // Structure: { day_1: { title, tasks: [] }, day_2: { ... } }
    roadmap: {
      type: Map,
      of: new mongoose.Schema(
        {
          title: String,
          tasks: [String],
        },
        { _id: false }
      ),
      required: true,
    },
  },
  { timestamps: true }
);

export default mongoose.model("UserRoadmap", userRoadmapSchema);